
version: '3.8'

services:
  # Base de datos MariaDB
  mariadb:
    image: mariadb:10.11
    container_name: mikrotik-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: mikrotik_dashboard
      MYSQL_USER: mikrotik_user
      MYSQL_PASSWORD: mikrotik_pass123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mikrotik-network

  # Aplicación web
  mikrotik-dashboard:
    build: .
    container_name: mikrotik-web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - mariadb
      - mikrotik-api
    networks:
      - mikrotik-network
    environment:
      - NODE_ENV=production

  # API backend
  mikrotik-api:
    build: ./api
    container_name: mikrotik-api
    restart: unless-stopped
    environment:
      DB_HOST: mariadb
      DB_USER: mikrotik_user
      DB_PASSWORD: mikrotik_pass123
      DB_NAME: mikrotik_dashboard
    depends_on:
      - mariadb
    ports:
      - "3000:3000"
    networks:
      - mikrotik-network


volumes:
  mariadb_data:
    driver: local

networks:
  mikrotik-network:
    driver: bridge
